[
  {
    "rule": "6.2 Caught exceptions: not ignored",
    "sub_rules": [
      {
        "sub_rule": "SR01_NoEmptyCaught",
        "content": "It is very rarely correct to do nothing in response to a caught exception. (Typical responses are to log it, or if it is considered \"impossible\", rethrow it as an AssertionError.)\n\nWhen it truly is appropriate to take no action whatsoever in a catch block, the reason this is justified is explained in a comment.",
        "relationship": "包含关系",
        "formalization": "empty_catch_block must contain explanation_comment"
      }
    ]
  }
]